// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylwlrhohidtztalltvny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlsd2xyaG9oaWR0enRhbGx0dm55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NzkyNzcsImV4cCI6MjA3MTI1NTI3N30.mWNjvTeGIskV9aRf25kDF-z_2msJIQ4sbKbhNOrEuqs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});